// 电脑配件价格监控 - 自动生成数据文件, 请勿手动编辑
// 生成时间: 2026-09-09 10:17:24
window.PRICE_DATA = {
  "latest": {
    "fetch_time": "2026-09-09T10:16:25.024795+08:00",
    "items": [
      {
        "id": "cpu_intel_i5_14600kf_jd",
        "category": "CPU",
        "model": "i5-14600KF",
        "platform": "京东",
        "url": "https://item.jd.com/100069427196.html",
        "price": 1499.0,
        "price_label": "到手价",
        "original_price": 1799.0,
        "status": "success",
        "note": "京东移动端(jdPrice), 原价1799.0"
      },
      {
        "id": "cpu_intel_i7_14700kf_jd",
        "category": "CPU",
        "model": "i7-14700KF",
        "platform": "京东",
        "url": "https://item.jd.com/100070072259.html",
        "price": 2519.0,
        "price_label": "到手价",
        "original_price": 3299.0,
        "status": "success",
        "note": "京东移动端(jdPrice), 原价3299.0"
      },
      {
        "id": "cpu_intel_i9_14900kf_jd",
        "category": "CPU",
        "model": "i9-14900KF",
        "platform": "京东",
        "url": "https://item.jd.com/100075321958.html",
        "price": 4799.0,
        "price_label": "到手价",
        "original_price": 4799.0,
        "status": "success",
        "note": "京东移动端(jdPrice), 原价4799.0"
      },
      {
        "id": "cpu_intel_i5_13400f_jd",
        "category": "CPU",
        "model": "i5-13400F",
        "platform": "京东",
        "url": "https://item.jd.com/100049450275.html",
        "price": 1199.0,
        "price_label": "到手价",
        "original_price": 1699.0,
        "status": "success",
        "note": "京东移动端(jdPrice), 原价1699.0"
      },
      {
        "id": "cpu_intel_i5_14600kf_smzdm",
        "category": "CPU",
        "model": "i5-14600KF",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=i5-14600KF",
        "price": 1499.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 英特尔 酷睿i5-14600KF CPU 3.5GHz 14核20线程  @京东"
      },
      {
        "id": "cpu_intel_i7_14700kf_smzdm",
        "category": "CPU",
        "model": "i7-14700KF",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=i7-14700KF",
        "price": 2927.54,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 英特尔 酷睿™ i7-14700KF 新款处理器 20 核(8 个 P 核 @京东"
      },
      {
        "id": "cpu_intel_i9_14900kf_smzdm",
        "category": "CPU",
        "model": "i9-14900KF",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=i9-14900KF",
        "price": 3399.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 英特尔 酷睿i9-14900KF CPU 3.2GHz 24核32线程  @京东"
      },
      {
        "id": "cpu_intel_i5_13400f_smzdm",
        "category": "CPU",
        "model": "i5-13400F",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=i5-13400F",
        "price": 4536.88,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 今日必买：七彩虹 i5-13400F RTX 5060  @京东"
      },
      {
        "id": "cpu_amd_r5_7500f_smzdm",
        "category": "CPU",
        "model": "R5 7500F",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R5-7500F",
        "price": 787.55,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 AMD 锐龙R5 7500F CPU 3.7GHz 6核12线程  @京东"
      },
      {
        "id": "cpu_amd_r7_9700x_smzdm",
        "category": "CPU",
        "model": "R7 9700X",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R7-9700X",
        "price": 1294.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 锐龙 AMD R7 9700X散片 8核16线程高性能台式机电竞处理器  @拼多多"
      },
      {
        "id": "cpu_amd_r5_5600_smzdm",
        "category": "CPU",
        "model": "R5 5600",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R5-5600",
        "price": 634.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 AMD RYZEN AMD锐龙R5 5600处理器六核心12线程台式电脑C @拼多多"
      },
      {
        "id": "cpu_amd_r7_7800x3d_smzdm",
        "category": "CPU",
        "model": "R7 7800X3D",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R7-7800X3D",
        "price": 1759.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 AMD 锐龙R7 7800X3D盒装处理器16线程全新8核CPU游戏电脑  @拼多多"
      },
      {
        "id": "mb_微星_b760m_mortar_wifi_ii_smzdm",
        "category": "主板",
        "model": "B760M MORTAR WIFI II",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%BE%AE%E6%98%9FB760M%E8%BF%AB%E5%87%BB%E7%82%AE",
        "price": 1049.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 微星 B760M MORTAR WIFI II DDR5 M-ATX主板（ @京东"
      },
      {
        "id": "mb_华硕_tuf_gaming_b760m_plus_wifi_d4_smzdm",
        "category": "主板",
        "model": "TUF GAMING B760M-PLUS WIFI D4",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95TUF%20B760M",
        "price": 1149.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 华硕 TUF GAMING B760M-PLUS WIFI D4 重炮手  @京东"
      },
      {
        "id": "mb_技嘉_b860m_aorus_pro_wifi_7_smzdm",
        "category": "主板",
        "model": "B860M AORUS PRO WIFI 7",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E6%8A%80%E5%98%89B860M",
        "price": 1369.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 技嘉 电竞雕B860M AORUS PRO WIFI7 DDR5主板 支持 @京东"
      },
      {
        "id": "mb_华硕_tuf_gaming_x670e_plus_wifi_smzdm",
        "category": "主板",
        "model": "TUF GAMING X670E-PLUS WIFI",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95X670E",
        "price": 2119.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 ASUS 华硕 TUF GAMING X670E-PLUS WIFI主板  @京东"
      },
      {
        "id": "gpu_七彩虹_rtx_4060_战斧_duo_8g_smzdm",
        "category": "显卡",
        "model": "RTX 4060 战斧 DUO 8G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B9RTX4060%E6%88%98%E6%96%A7",
        "price": 2024.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 COLORFUL 七彩虹 GeForce RTX 4060 战斧DUO 8 @淘宝"
      },
      {
        "id": "gpu_华硕_dual_rtx4070_o12g_smzdm",
        "category": "显卡",
        "model": "DUAL RTX4070 O12G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95DUAL%20RTX4070",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[DUAL RTX4070 O12G]"
      },
      {
        "id": "gpu_华硕_tuf_rtx_4070_super_o12g_smzdm",
        "category": "显卡",
        "model": "TUF RTX 4070 SUPER O12G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95RTX4070SUPER",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[TUF RTX 4070 SUPER O12G]"
      },
      {
        "id": "gpu_七彩虹_igame_rtx_4070_ti_super_vulcan_w_oc_smzdm",
        "category": "显卡",
        "model": "iGame RTX 4070 Ti SUPER Vulcan W OC",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B94070TiS%E7%81%AB%E7%A5%9E",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[iGame RTX 4070 Ti SUPER Vulcan W OC]"
      },
      {
        "id": "gpu_七彩虹_igame_rtx_4070_super_ultra_w_oc_smzdm",
        "category": "显卡",
        "model": "iGame RTX 4070 SUPER Ultra W OC",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B94070SUltra",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[iGame RTX 4070 SUPER Ultra W OC]"
      },
      {
        "id": "gpu_影驰_rtx_4070_ti_super_金属大师_oc_smzdm",
        "category": "显卡",
        "model": "RTX 4070 Ti SUPER 金属大师 OC",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%BD%B1%E9%A9%B04070TiS%E9%87%91%E5%B1%9E%E5%A4%A7%E5%B8%88",
        "price": 6182.5,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 GALAXY 影驰 GeForce RTX4070TI SUPER名人堂  @京东"
      },
      {
        "id": "ram_金百达_ddr5_6000_16gbx2_银爵_smzdm",
        "category": "内存",
        "model": "DDR5 6000 16GBx2 银爵",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E7%99%BE%E8%BE%BEDDR5%206000",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[DDR5 6000 16GBx2 银爵]"
      },
      {
        "id": "ram_芝奇_ddr5_6000_16gx2_焰刃_黯夜黑_smzdm",
        "category": "内存",
        "model": "DDR5 6000 16Gx2 焰刃 黯夜黑",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%8A%9D%E5%A5%87DDR5%206000%E7%84%B0%E5%88%83",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[DDR5 6000 16Gx2 焰刃 黯夜黑]"
      },
      {
        "id": "ram_金士顿_fury_ddr5_6000_16gb_野兽_smzdm",
        "category": "内存",
        "model": "FURY DDR5 6000 16GB 野兽",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFFURY%20DDR5%206000",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[FURY DDR5 6000 16GB 野兽]"
      },
      {
        "id": "ssd_三星_990_pro_1tb_smzdm",
        "category": "固态硬盘",
        "model": "990 PRO 1TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B8%89%E6%98%9F990PRO",
        "price": 1589.12,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 Samsung 三星 990 PRO 1TB固态硬盘 PCIe4.0 NV @亚马逊"
      },
      {
        "id": "ssd_致态_tiplus7100_1tb_smzdm",
        "category": "固态硬盘",
        "model": "TiPlus7100 1TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%87%B4%E6%80%81TiPlus7100",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[TiPlus7100 1TB]"
      },
      {
        "id": "ssd_西部数据_sn850x_1tb_smzdm",
        "category": "固态硬盘",
        "model": "SN850X 1TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=WD%20SN850X",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[SN850X 1TB]"
      },
      {
        "id": "ssd_金士顿_nv3_1tb_smzdm",
        "category": "固态硬盘",
        "model": "NV3 1TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFNV3",
        "price": 1090.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 金士顿 SSD固态硬盘 M.2 NVMe PCIe 4.0×4 NV3 1 @京东"
      },
      {
        "id": "ssd_致态_tiplus7100s_1tb_smzdm",
        "category": "固态硬盘",
        "model": "TiPlus7100s 1TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%87%B4%E6%80%81TiPlus7100s",
        "price": 729.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 技嘉 宏碁 GM7 致态Tiplus7100s 1TB 2TB 佰维 光威 @天猫精选"
      },
      {
        "id": "hdd_希捷_酷鹰_4tb_st4000vx015_smzdm",
        "category": "机械硬盘",
        "model": "酷鹰 4TB ST4000VX015",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E9%B9%B04TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[酷鹰 4TB ST4000VX015]"
      },
      {
        "id": "hdd_西部数据_蓝盘_4tb_wd40ezax_smzdm",
        "category": "机械硬盘",
        "model": "蓝盘 4TB WD40EZAX",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%A5%BF%E6%95%B0%E8%93%9D%E7%9B%984TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[蓝盘 4TB WD40EZAX]"
      },
      {
        "id": "hdd_希捷_酷鱼_4tb_st4000dm004_smzdm",
        "category": "机械硬盘",
        "model": "酷鱼 4TB ST4000DM004",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E9%B1%BC4TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[酷鱼 4TB ST4000DM004]"
      },
      {
        "id": "psu_海韵_focus_gx_750_smzdm",
        "category": "电源",
        "model": "FOCUS GX-750",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E6%B5%B7%E9%9F%B5GX750",
        "price": 641.61,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 PLUS会员：Seasonic 海韵 FOCUS GX750W电源 ATX @京东"
      },
      {
        "id": "psu_长城_x7_750w_atx3_1_smzdm",
        "category": "电源",
        "model": "X7 750W ATX3.1",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%95%BF%E5%9F%8EX7%20750W",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[X7 750W ATX3.1]"
      },
      {
        "id": "psu_安钛克_ne750_金牌全模组_smzdm",
        "category": "电源",
        "model": "NE750 金牌全模组",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE750",
        "price": 469.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 安钛克 NE750 金牌（90%）全模组ATX电源 750W 黑色  @京东"
      },
      {
        "id": "psu_安钛克_ne850_纯白色金牌全模_smzdm",
        "category": "电源",
        "model": "NE850 纯白色金牌全模",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE850",
        "price": 496.36,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 安钛克 NE850 金牌（90%）全模组ATX电源 850W 黑白  @京东"
      },
      {
        "id": "psu_利民_tr_sg750_atx3_1_smzdm",
        "category": "电源",
        "model": "TR-SG750 ATX3.1",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91SG750",
        "price": 302.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 利民 额定750W TR-SG750 ATX3.1电源 金牌全模组电源 P @京东"
      },
      {
        "id": "psu_华硕_prime_750g_金牌全模组_smzdm",
        "category": "电源",
        "model": "PRIME 750G 金牌全模组",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95PRIME%20750G",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[PRIME 750G 金牌全模组]"
      },
      {
        "id": "psu_安钛克_ne1000_白色金牌全模_smzdm",
        "category": "电源",
        "model": "NE1000 白色金牌全模",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE1000",
        "price": 903.31,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 安钛克 NE系列 NE1000 金牌（90%）全模组电源 1000W  @京东"
      },
      {
        "id": "case_追风者_p400a_黑色_smzdm",
        "category": "机箱",
        "model": "P400A 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%BF%BD%E9%A3%8E%E8%80%85P400A",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[P400A 黑色]"
      },
      {
        "id": "case_乔思伯_松果d41_标准版黑色_smzdm",
        "category": "机箱",
        "model": "松果D41 标准版黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B9%94%E6%80%9D%E4%BC%AFD41",
        "price": 225.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 JONSBO 乔思伯 松果D41 标准版黑色 ATX机箱  @京东"
      },
      {
        "id": "case_先马_趣造2_黑色_smzdm",
        "category": "机箱",
        "model": "趣造2 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%85%88%E9%A9%AC%E8%B6%A3%E9%80%A02",
        "price": 549.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 SAMA 先马 XW280（无风扇版）趣造2黑色 一体式机  @京东"
      },
      {
        "id": "case_航嘉_s960_暴风雪x_黑色_smzdm",
        "category": "机箱",
        "model": "S960 暴风雪X 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%88%AA%E5%98%89S960%E6%9A%B4%E9%A3%8E%E9%9B%AA",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[S960 暴风雪X 黑色]"
      },
      {
        "id": "case_航嘉_s960_暴风雪x_白色_smzdm",
        "category": "机箱",
        "model": "S960 暴风雪X 白色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%88%AA%E5%98%89S960%E7%99%BD%E8%89%B2",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[S960 暴风雪X 白色]"
      },
      {
        "id": "case_先马_趣造2_air_黑色_smzdm",
        "category": "机箱",
        "model": "趣造2 Air 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%85%88%E9%A9%AC%E8%B6%A3%E9%80%A02Air",
        "price": 199.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 先马 趣造2air黑色 桌面matx台式电脑小机箱  @京东"
      },
      {
        "id": "cooler_利民_pa120_se_argb_smzdm",
        "category": "CPU散热器",
        "model": "PA120 SE ARGB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91PA120",
        "price": 177.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 利民 PA120SE ARGB 155mm 风冷散热器 白色  @京东"
      },
      {
        "id": "cooler_九州风神_冰堡垒360_数显版_smzdm",
        "category": "CPU散热器",
        "model": "冰堡垒360 数显版",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B9%9D%E5%B7%9E%E9%A3%8E%E7%A5%9E%E5%86%B0%E5%A0%A1%E5%9E%92360",
        "price": 699.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 文章 用九州风神冰堡垒360数显版！还有什么U压不住？ 使用评测风扇噪音数码配件 @"
      },
      {
        "id": "cooler_瓦尔基里_c360_rgb_smzdm",
        "category": "CPU散热器",
        "model": "C360-RGB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CC360",
        "price": 386.19,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 瓦尔基里 C360-RGB ARGB 65mm 一体式水冷散热器 黑色  @京东"
      },
      {
        "id": "cooler_瓦尔基里_gl360_smzdm",
        "category": "CPU散热器",
        "model": "GL360",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CGL360",
        "price": 619.1,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 瓦尔基里 GL360 VK 360MM 一体式水冷散热器 钛黑  @京东"
      },
      {
        "id": "cooler_瓦尔基里_c360w_rgb_白色_smzdm",
        "category": "CPU散热器",
        "model": "C360W-RGB 白色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CC360%E7%99%BD%E8%89%B2",
        "price": 529.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 VALKYRIE 瓦尔基里 C360W-RGB 一体式水冷散热器 白色  @京东"
      },
      {
        "id": "fan_利民_tl_c12c_smzdm",
        "category": "机箱风扇",
        "model": "TL-C12C",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91TL-C12C",
        "price": 45.9,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 利民 TL-C12C 120mm 机箱散热风扇 3个装  @京东"
      },
      {
        "id": "fan_猫头鹰_nf_a12x25_pwm_smzdm",
        "category": "机箱风扇",
        "model": "NF-A12x25 PWM",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%8C%AB%E5%A4%B4%E9%B9%B0NF-A12x25",
        "price": 180.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 noctua 猫头鹰 NF-A12x25 PWM 120mm 机箱散热风扇 @天猫精选"
      },
      {
        "id": "fan_联力_积木风扇_sl120_3b_黑色_smzdm",
        "category": "机箱风扇",
        "model": "积木风扇 SL120-3B 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%81%94%E5%8A%9B%E7%A7%AF%E6%9C%A8%E9%A3%8E%E6%89%87SL120",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[积木风扇 SL120-3B 黑色]"
      },
      {
        "id": "fan_利民_tl_p12_s_argb_smzdm",
        "category": "机箱风扇",
        "model": "TL-P12-S ARGB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91TL-P12-S",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[TL-P12-S ARGB]"
      },
      {
        "id": "fan_联力_积木风扇三代无线版_黑色_smzdm",
        "category": "机箱风扇",
        "model": "积木风扇三代无线版 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%81%94%E5%8A%9B%E7%A7%AF%E6%9C%A8%E9%A3%8E%E6%89%87%E4%B8%89%E4%BB%A3",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[积木风扇三代无线版 黑色]"
      },
      {
        "id": "monitor_戴尔_u2723qe_27英寸_4k_smzdm",
        "category": "显示器",
        "model": "U2723QE 27英寸 4K",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E6%88%B4%E5%B0%94U2723QE",
        "price": 3599.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 DELL 戴尔 U2723QE 27英寸 4K超高清 IPS Black屏 @京东"
      },
      {
        "id": "monitor_aoc_q27g40e_ws_27英寸_2k_180hz_smzdm",
        "category": "显示器",
        "model": "Q27G40E/WS 27英寸 2K 180Hz",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=AOC%20Q27G40E",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[Q27G40E/WS 27英寸 2K 180Hz]"
      },
      {
        "id": "monitor_微星_pro_max_271qphw_e14_27英寸_2k_smzdm",
        "category": "显示器",
        "model": "PRO MAX 271QPHW E14 27英寸 2K",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%BE%AE%E6%98%9FPRO%20MAX%20271QPHW",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[PRO MAX 271QPHW E14 27英寸 2K]"
      },
      {
        "id": "monitor_飞利浦_evnia_27m2n6550pf_27英寸_woled_smzdm",
        "category": "显示器",
        "model": "EVNIA 27M2N6550PF 27英寸 WOLED",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%A3%9E%E5%88%A9%E6%B5%A627M2N6550PF",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[EVNIA 27M2N6550PF 27英寸 WOLED]"
      },
      {
        "id": "keyboard_罗技_g610_机械键盘_红轴_smzdm",
        "category": "键盘",
        "model": "G610 机械键盘 红轴",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G610",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[G610 机械键盘 红轴]"
      },
      {
        "id": "keyboard_樱桃_mx_3_0s_tkl_红轴_smzdm",
        "category": "键盘",
        "model": "MX 3.0S TKL 红轴",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E6%A8%B1%E6%A1%83MX3.0S",
        "price": 423.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 CHERRY 樱桃 MX3.0S TKL有线机械键盘RGB游戏电竞黑 青  @天猫精选"
      },
      {
        "id": "keyboard_雷蛇_黑寡妇v3_竞技版_绿轴_smzdm",
        "category": "键盘",
        "model": "黑寡妇V3 竞技版 绿轴",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%9B%B7%E8%9B%87%E9%BB%91%E5%AF%A1%E5%A6%87V3",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[黑寡妇V3 竞技版 绿轴]"
      },
      {
        "id": "keyboard_vgn_v98pro_v3_冰川轴_smzdm",
        "category": "键盘",
        "model": "V98Pro V3 冰川轴",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=VGN%20V98Pro",
        "price": 228.1,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 国家补贴：VGN V98Pro V3客制化机械键盘99键无线蓝牙有线三模长 @京东"
      },
      {
        "id": "mouse_罗技_g502_hero_主宰者_smzdm",
        "category": "鼠标",
        "model": "G502 HERO 主宰者",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G502",
        "price": 126.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 罗技 G502 HERO 主宰者 有线鼠标 16000DPI RGB  @天猫精选"
      },
      {
        "id": "mouse_雷蛇_毒蝰v2_pro_专业版_smzdm",
        "category": "鼠标",
        "model": "毒蝰V2 Pro 专业版",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%9B%B7%E8%9B%87%E6%AF%92%E8%9D%B0V2Pro",
        "price": 574.15,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 雷蛇 毒蝰 V2 Pro 专业版 2.4G双模无线鼠标 30000DPI  @京东"
      },
      {
        "id": "mouse_罗技_g_pro_x_superlight_二代_黑色_smzdm",
        "category": "鼠标",
        "model": "G PRO X SUPERLIGHT 二代 黑色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80GPW%E4%BA%8C%E4%BB%A3",
        "price": 569.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 logitech 罗技 G） PRO X SUPERLIGHT无线游戏鼠标 @京东"
      },
      {
        "id": "mouse_罗技_g304_白色_smzdm",
        "category": "鼠标",
        "model": "G304 白色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G304",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[G304 白色]"
      },
      {
        "id": "mouse_达尔优_a900_白色_smzdm",
        "category": "鼠标",
        "model": "A900 白色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E8%BE%BE%E5%B0%94%E4%BC%98A900",
        "price": 197.84,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 创维 取暖器石墨烯速热暖风机家用智能温控语音电暖器大面积升温卧室轻音节能暖 @京东"
      },
      {
        "id": "ram_金士顿_fury_64gb_32gx2__ddr5_6000_超级野兽_白色_smzdm",
        "category": "内存",
        "model": "FURY 64GB(32Gx2) DDR5 6000 超级野兽 白色",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFFURY%20DDR5%206000%2032Gx2",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[FURY 64GB(32Gx2) DDR5 6000 超级野兽 白色]"
      },
      {
        "id": "ram_威刚_xpg_龙耀_64g_32gx2__ddr5_6400_d500g_smzdm",
        "category": "内存",
        "model": "XPG 龙耀 64G(32Gx2) DDR5 6400 D500G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%A8%81%E5%88%9AXPG%E9%BE%99%E8%80%80DDR5%206400",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[XPG 龙耀 64G(32Gx2) DDR5 6400 D500G]"
      },
      {
        "id": "hdd_东芝_p300_3tb_hdwd130_smzdm",
        "category": "机械硬盘",
        "model": "P300 3TB HDWD130",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E4%B8%9C%E8%8A%9DP300%203TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[P300 3TB HDWD130]"
      },
      {
        "id": "hdd_希捷_酷狼pro_4tb_st4000nt001_smzdm",
        "category": "机械硬盘",
        "model": "酷狼PRO 4TB ST4000NT001",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E7%8B%BCPRO%204TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[酷狼PRO 4TB ST4000NT001]"
      },
      {
        "id": "mb_技嘉_b760m_aorus_elite_ax_小雕_ddr5_smzdm",
        "category": "主板",
        "model": "B760M AORUS ELITE AX 小雕 DDR5",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=%E6%8A%80%E5%98%89B760M%E5%B0%8F%E9%9B%95",
        "price": 1099.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 技嘉 B760雕妹主板DDR5 WIFI B760M AORUS ELIT @京东"
      },
      {
        "id": "monitor_ktc_h27v22_27英寸_2k_165hz_smzdm",
        "category": "显示器",
        "model": "H27V22 27英寸 2K 165Hz",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=KTC%20H27V22",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[H27V22 27英寸 2K 165Hz]"
      },
      {
        "id": "keyboard_rk_r98_三模_烟雨轴v2_火蓝_smzdm",
        "category": "键盘",
        "model": "R98 三模 烟雨轴V2 火蓝",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RK%20R98",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[R98 三模 烟雨轴V2 火蓝]"
      },
      {
        "id": "CPU_AMD_r7_9800x3d_jd",
        "category": "CPU",
        "model": "R7 9800X3D",
        "platform": "京东",
        "url": "",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "京东搜索未匹配型号[R7 9800X3D]",
        "offers": []
      },
      {
        "id": "CPU_AMD_r9_9950x3d_jd",
        "category": "CPU",
        "model": "R9 9950X3D",
        "platform": "京东",
        "url": "",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "京东搜索未匹配型号[R9 9950X3D]",
        "offers": []
      },
      {
        "id": "CPU_Intel_core_ultra_285k_jd",
        "category": "CPU",
        "model": "Core Ultra 285K",
        "platform": "京东",
        "url": "",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "京东搜索未匹配型号[Core Ultra 285K]",
        "offers": []
      },
      {
        "id": "CPU_AMD_r7_9800x3d_smzdm",
        "category": "CPU",
        "model": "R7 9800X3D",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R7%209800X3D",
        "price": 2619.15,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程  @京东",
        "offers": [
          {
            "price": 2619.15,
            "shop": "京东",
            "time": "06-17 21:27",
            "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
          },
          {
            "price": 2329.0,
            "shop": "拼多多",
            "time": "08-26 13:37",
            "title": "好价 AMD 锐龙 R7 9800X3D散片8核16线程高性能电竞处理器 "
          },
          {
            "price": 2969.0,
            "shop": "京东",
            "time": "09-08 10:45",
            "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
          },
          {
            "price": 2709.15,
            "shop": "京东",
            "time": "06-17 21:12",
            "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
          },
          {
            "price": 2879.1,
            "shop": "京东",
            "time": "06-28 03:10",
            "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
          }
        ]
      },
      {
        "id": "CPU_AMD_r9_9950x3d_smzdm",
        "category": "CPU",
        "model": "R9 9950X3D",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=R9%209950X3D",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[R9 9950X3D]",
        "offers": []
      },
      {
        "id": "CPU_Intel_core_ultra_285k_smzdm",
        "category": "CPU",
        "model": "Core Ultra 285K",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=Core%20Ultra%20285K",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[Core Ultra 285K]",
        "offers": []
      },
      {
        "id": "CPU_Intel_i5-12600kf_smzdm",
        "category": "CPU",
        "model": "i5-12600KF",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=i5-12600KF",
        "price": 834.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 英特尔酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 @拼多多",
        "offers": [
          {
            "price": 834.0,
            "shop": "拼多多",
            "time": "09-01 15:43",
            "title": "好价 英特尔酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 "
          },
          {
            "price": 994.0,
            "shop": "京东",
            "time": null,
            "title": "好价 英特尔 酷睿i5-12600KF CPU 4.9Ghz 10核16线程 "
          },
          {
            "price": 874.0,
            "shop": "拼多多",
            "time": "08-13 18:49",
            "title": "好价 i5 12600KF盒装 酷睿12代 10核16线程全新正品官方联保 "
          },
          {
            "price": 979.0,
            "shop": "京东",
            "time": null,
            "title": "好价 英特尔 酷睿i5-12600KF CPU 4.9Ghz 10核16线程 "
          },
          {
            "price": 864.0,
            "shop": "拼多多",
            "time": "08-23 23:52",
            "title": "好价 英特尔 酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 "
          }
        ]
      },
      {
        "id": "显卡_NVIDIA_rtx_5060ti_16g_smzdm",
        "category": "显卡",
        "model": "RTX 5060Ti 16G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RTX%205060Ti%2016G",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[RTX 5060Ti 16G]",
        "offers": []
      },
      {
        "id": "显卡_NVIDIA_rtx_5070_12g_smzdm",
        "category": "显卡",
        "model": "RTX 5070 12G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RTX%205070%2012G",
        "price": 5599.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 微星 魔龙 GeForce RTX 5070 12G GAMING TRI @京东",
        "offers": [
          {
            "price": 5599.0,
            "shop": "京东",
            "time": "07-19 10:16",
            "title": "好价 微星 魔龙 GeForce RTX 5070 12G GAMING TRIO OC 显卡 "
          }
        ]
      },
      {
        "id": "显卡_NVIDIA_rtx_5070ti_16g_smzdm",
        "category": "显卡",
        "model": "RTX 5070Ti 16G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RTX%205070Ti%2016G",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[RTX 5070Ti 16G]",
        "offers": []
      },
      {
        "id": "显卡_NVIDIA_rtx_5080_16g_smzdm",
        "category": "显卡",
        "model": "RTX 5080 16G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RTX%205080%2016G",
        "price": 13606.43,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC @京东",
        "offers": [
          {
            "price": 13606.43,
            "shop": "京东",
            "time": "09-08 11:36",
            "title": "好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC 16G 显卡 "
          },
          {
            "price": 13606.43,
            "shop": "京东",
            "time": "09-05 12:50",
            "title": "好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC 16G 显卡 "
          },
          {
            "price": 10996.0,
            "shop": "京东",
            "time": "06-26 16:33",
            "title": "好价 微星 魔龙 GeForce RTX 5080 16G GAMING TRIO OC 显卡 "
          },
          {
            "price": 10999.0,
            "shop": "京东",
            "time": "07-20 17:26",
            "title": "好价 微星 魔龙 GeForce RTX 5080 16G GAMING TRIO OC 显卡 "
          }
        ]
      },
      {
        "id": "显卡_NVIDIA_rtx_5090_32g_smzdm",
        "category": "显卡",
        "model": "RTX 5090 32G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RTX%205090%2032G",
        "price": 11099.0,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 赋欣U7 270K 深度学习支持双卡RTX 5090 32G GPU服务器 @京东",
        "offers": [
          {
            "price": 11099.0,
            "shop": "京东",
            "time": "07-23 18:46",
            "title": "好价 赋欣U7 270K 深度学习支持双卡RTX 5090 32G GPU服务器 OpenClawAI仿真模拟水冷工作站"
          },
          {
            "price": 38399.0,
            "shop": "京东",
            "time": "07-30 13:30",
            "title": "好价 cloud hin 云轩深度学习工作站GPU显卡 RTX 5090 32G涡轮显卡 "
          }
        ]
      },
      {
        "id": "显卡_AMD_rx_9070xt_16g_smzdm",
        "category": "显卡",
        "model": "RX 9070XT 16G",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=RX%209070XT%2016G",
        "price": 4293.05,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏 @天猫精选",
        "offers": [
          {
            "price": 4293.05,
            "shop": "天猫精选",
            "time": "06-16 11:30",
            "title": "好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
          },
          {
            "price": 3899.0,
            "shop": "抖音商城",
            "time": "06-15 13:32",
            "title": "好价 盈通 RX9070XT 16G 大地之神电竞游戏直播剪辑台式机电脑独立显卡 "
          },
          {
            "price": 4293.05,
            "shop": "天猫精选",
            "time": "06-12 14:15",
            "title": "好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
          },
          {
            "price": 4121.53,
            "shop": "天猫精选",
            "time": "06-12 15:42",
            "title": "好价 国家补贴：盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
          }
        ]
      },
      {
        "id": "固态硬盘_Samsung_990_pro_2tb_smzdm",
        "category": "固态硬盘",
        "model": "990 PRO 2TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=990%20PRO%202TB",
        "price": 2541.86,
        "price_label": "到手价",
        "original_price": null,
        "status": "success",
        "note": "SMZDM匹配: 好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVM @亚马逊",
        "offers": [
          {
            "price": 2541.86,
            "shop": "亚马逊",
            "time": "06-23 12:46",
            "title": "好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVMe高速传输 M.2 SSD 读速7450"
          },
          {
            "price": 2550.3,
            "shop": "亚马逊",
            "time": "08-21 09:09",
            "title": "好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVMe高速传输 M.2 SSD 读速7450"
          }
        ]
      },
      {
        "id": "固态硬盘_致态_tipro9000_2tb_smzdm",
        "category": "固态硬盘",
        "model": "TiPro9000 2TB",
        "platform": "什么值得买",
        "url": "https://search.smzdm.com/?c=home&s=TiPro9000%202TB",
        "price": null,
        "price_label": null,
        "original_price": null,
        "status": "failed",
        "note": "SMZDM未匹配到型号[TiPro9000 2TB]",
        "offers": []
      }
    ]
  },
  "history": [
    {
      "fetch_time": "2026-09-09T09:46:33.517920+08:00",
      "items": [
        {
          "id": "cpu_intel_i5_14600kf_jd",
          "category": "CPU",
          "model": "i5-14600KF",
          "platform": "京东",
          "url": "https://item.jd.com/100069427196.html",
          "price": 1499.0,
          "price_label": "到手价",
          "original_price": 1799.0,
          "status": "success",
          "note": "京东移动端(jdPrice), 原价1799.0"
        },
        {
          "id": "cpu_intel_i7_14700kf_jd",
          "category": "CPU",
          "model": "i7-14700KF",
          "platform": "京东",
          "url": "https://item.jd.com/100070072259.html",
          "price": 2519.0,
          "price_label": "到手价",
          "original_price": 3299.0,
          "status": "success",
          "note": "京东移动端(jdPrice), 原价3299.0"
        },
        {
          "id": "cpu_intel_i9_14900kf_jd",
          "category": "CPU",
          "model": "i9-14900KF",
          "platform": "京东",
          "url": "https://item.jd.com/100075321958.html",
          "price": 4799.0,
          "price_label": "到手价",
          "original_price": 4799.0,
          "status": "success",
          "note": "京东移动端(jdPrice), 原价4799.0"
        },
        {
          "id": "cpu_intel_i5_13400f_jd",
          "category": "CPU",
          "model": "i5-13400F",
          "platform": "京东",
          "url": "https://item.jd.com/100049450275.html",
          "price": 1199.0,
          "price_label": "到手价",
          "original_price": 1699.0,
          "status": "success",
          "note": "京东移动端(jdPrice), 原价1699.0"
        },
        {
          "id": "cpu_intel_i5_14600kf_smzdm",
          "category": "CPU",
          "model": "i5-14600KF",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=i5-14600KF",
          "price": 1499.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 英特尔 酷睿i5-14600KF CPU 3.5GHz 14核20线程  @京东"
        },
        {
          "id": "cpu_intel_i7_14700kf_smzdm",
          "category": "CPU",
          "model": "i7-14700KF",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=i7-14700KF",
          "price": 2927.54,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 英特尔 酷睿™ i7-14700KF 新款处理器 20 核(8 个 P 核 @京东"
        },
        {
          "id": "cpu_intel_i9_14900kf_smzdm",
          "category": "CPU",
          "model": "i9-14900KF",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=i9-14900KF",
          "price": 3399.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 英特尔 酷睿i9-14900KF CPU 3.2GHz 24核32线程  @京东"
        },
        {
          "id": "cpu_intel_i5_13400f_smzdm",
          "category": "CPU",
          "model": "i5-13400F",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=i5-13400F",
          "price": 4536.88,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 今日必买：七彩虹 i5-13400F RTX 5060  @京东"
        },
        {
          "id": "cpu_amd_r5_7500f_smzdm",
          "category": "CPU",
          "model": "R5 7500F",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R5-7500F",
          "price": 787.55,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 AMD 锐龙R5 7500F CPU 3.7GHz 6核12线程  @京东"
        },
        {
          "id": "cpu_amd_r7_9700x_smzdm",
          "category": "CPU",
          "model": "R7 9700X",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R7-9700X",
          "price": 1294.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 锐龙 AMD R7 9700X散片 8核16线程高性能台式机电竞处理器  @拼多多"
        },
        {
          "id": "cpu_amd_r5_5600_smzdm",
          "category": "CPU",
          "model": "R5 5600",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R5-5600",
          "price": 634.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 AMD RYZEN AMD锐龙R5 5600处理器六核心12线程台式电脑C @拼多多"
        },
        {
          "id": "cpu_amd_r7_7800x3d_smzdm",
          "category": "CPU",
          "model": "R7 7800X3D",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R7-7800X3D",
          "price": 1759.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 AMD 锐龙R7 7800X3D盒装处理器16线程全新8核CPU游戏电脑  @拼多多"
        },
        {
          "id": "mb_微星_b760m_mortar_wifi_ii_smzdm",
          "category": "主板",
          "model": "B760M MORTAR WIFI II",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%BE%AE%E6%98%9FB760M%E8%BF%AB%E5%87%BB%E7%82%AE",
          "price": 1049.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 微星 B760M MORTAR WIFI II DDR5 M-ATX主板（ @京东"
        },
        {
          "id": "mb_华硕_tuf_gaming_b760m_plus_wifi_d4_smzdm",
          "category": "主板",
          "model": "TUF GAMING B760M-PLUS WIFI D4",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95TUF%20B760M",
          "price": 1149.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 华硕 TUF GAMING B760M-PLUS WIFI D4 重炮手  @京东"
        },
        {
          "id": "mb_技嘉_b860m_aorus_pro_wifi_7_smzdm",
          "category": "主板",
          "model": "B860M AORUS PRO WIFI 7",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E6%8A%80%E5%98%89B860M",
          "price": 1369.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 技嘉 电竞雕B860M AORUS PRO WIFI7 DDR5主板 支持 @京东"
        },
        {
          "id": "mb_华硕_tuf_gaming_x670e_plus_wifi_smzdm",
          "category": "主板",
          "model": "TUF GAMING X670E-PLUS WIFI",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95X670E",
          "price": 2119.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 ASUS 华硕 TUF GAMING X670E-PLUS WIFI主板  @京东"
        },
        {
          "id": "gpu_七彩虹_rtx_4060_战斧_duo_8g_smzdm",
          "category": "显卡",
          "model": "RTX 4060 战斧 DUO 8G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B9RTX4060%E6%88%98%E6%96%A7",
          "price": 2024.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 COLORFUL 七彩虹 GeForce RTX 4060 战斧DUO 8 @淘宝"
        },
        {
          "id": "gpu_华硕_dual_rtx4070_o12g_smzdm",
          "category": "显卡",
          "model": "DUAL RTX4070 O12G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95DUAL%20RTX4070",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[DUAL RTX4070 O12G]"
        },
        {
          "id": "gpu_华硕_tuf_rtx_4070_super_o12g_smzdm",
          "category": "显卡",
          "model": "TUF RTX 4070 SUPER O12G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95RTX4070SUPER",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[TUF RTX 4070 SUPER O12G]"
        },
        {
          "id": "gpu_七彩虹_igame_rtx_4070_ti_super_vulcan_w_oc_smzdm",
          "category": "显卡",
          "model": "iGame RTX 4070 Ti SUPER Vulcan W OC",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B94070TiS%E7%81%AB%E7%A5%9E",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[iGame RTX 4070 Ti SUPER Vulcan W OC]"
        },
        {
          "id": "gpu_七彩虹_igame_rtx_4070_super_ultra_w_oc_smzdm",
          "category": "显卡",
          "model": "iGame RTX 4070 SUPER Ultra W OC",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B8%83%E5%BD%A9%E8%99%B94070SUltra",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[iGame RTX 4070 SUPER Ultra W OC]"
        },
        {
          "id": "gpu_影驰_rtx_4070_ti_super_金属大师_oc_smzdm",
          "category": "显卡",
          "model": "RTX 4070 Ti SUPER 金属大师 OC",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%BD%B1%E9%A9%B04070TiS%E9%87%91%E5%B1%9E%E5%A4%A7%E5%B8%88",
          "price": 6182.5,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 GALAXY 影驰 GeForce RTX4070TI SUPER名人堂  @京东"
        },
        {
          "id": "ram_金百达_ddr5_6000_16gbx2_银爵_smzdm",
          "category": "内存",
          "model": "DDR5 6000 16GBx2 银爵",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E7%99%BE%E8%BE%BEDDR5%206000",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[DDR5 6000 16GBx2 银爵]"
        },
        {
          "id": "ram_芝奇_ddr5_6000_16gx2_焰刃_黯夜黑_smzdm",
          "category": "内存",
          "model": "DDR5 6000 16Gx2 焰刃 黯夜黑",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%8A%9D%E5%A5%87DDR5%206000%E7%84%B0%E5%88%83",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[DDR5 6000 16Gx2 焰刃 黯夜黑]"
        },
        {
          "id": "ram_金士顿_fury_ddr5_6000_16gb_野兽_smzdm",
          "category": "内存",
          "model": "FURY DDR5 6000 16GB 野兽",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFFURY%20DDR5%206000",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[FURY DDR5 6000 16GB 野兽]"
        },
        {
          "id": "ssd_三星_990_pro_1tb_smzdm",
          "category": "固态硬盘",
          "model": "990 PRO 1TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B8%89%E6%98%9F990PRO",
          "price": 1589.12,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 Samsung 三星 990 PRO 1TB固态硬盘 PCIe4.0 NV @亚马逊"
        },
        {
          "id": "ssd_致态_tiplus7100_1tb_smzdm",
          "category": "固态硬盘",
          "model": "TiPlus7100 1TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%87%B4%E6%80%81TiPlus7100",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[TiPlus7100 1TB]"
        },
        {
          "id": "ssd_西部数据_sn850x_1tb_smzdm",
          "category": "固态硬盘",
          "model": "SN850X 1TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=WD%20SN850X",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[SN850X 1TB]"
        },
        {
          "id": "ssd_金士顿_nv3_1tb_smzdm",
          "category": "固态硬盘",
          "model": "NV3 1TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFNV3",
          "price": 1090.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 金士顿 SSD固态硬盘 M.2 NVMe PCIe 4.0×4 NV3 1 @京东"
        },
        {
          "id": "ssd_致态_tiplus7100s_1tb_smzdm",
          "category": "固态硬盘",
          "model": "TiPlus7100s 1TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%87%B4%E6%80%81TiPlus7100s",
          "price": 729.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 技嘉 宏碁 GM7 致态Tiplus7100s 1TB 2TB 佰维 光威 @天猫精选"
        },
        {
          "id": "hdd_希捷_酷鹰_4tb_st4000vx015_smzdm",
          "category": "机械硬盘",
          "model": "酷鹰 4TB ST4000VX015",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E9%B9%B04TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[酷鹰 4TB ST4000VX015]"
        },
        {
          "id": "hdd_西部数据_蓝盘_4tb_wd40ezax_smzdm",
          "category": "机械硬盘",
          "model": "蓝盘 4TB WD40EZAX",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%A5%BF%E6%95%B0%E8%93%9D%E7%9B%984TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[蓝盘 4TB WD40EZAX]"
        },
        {
          "id": "hdd_希捷_酷鱼_4tb_st4000dm004_smzdm",
          "category": "机械硬盘",
          "model": "酷鱼 4TB ST4000DM004",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E9%B1%BC4TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[酷鱼 4TB ST4000DM004]"
        },
        {
          "id": "psu_海韵_focus_gx_750_smzdm",
          "category": "电源",
          "model": "FOCUS GX-750",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E6%B5%B7%E9%9F%B5GX750",
          "price": 641.61,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 PLUS会员：Seasonic 海韵 FOCUS GX750W电源 ATX @京东"
        },
        {
          "id": "psu_长城_x7_750w_atx3_1_smzdm",
          "category": "电源",
          "model": "X7 750W ATX3.1",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%95%BF%E5%9F%8EX7%20750W",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[X7 750W ATX3.1]"
        },
        {
          "id": "psu_安钛克_ne750_金牌全模组_smzdm",
          "category": "电源",
          "model": "NE750 金牌全模组",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE750",
          "price": 469.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 安钛克 NE750 金牌（90%）全模组ATX电源 750W 黑色  @京东"
        },
        {
          "id": "psu_安钛克_ne850_纯白色金牌全模_smzdm",
          "category": "电源",
          "model": "NE850 纯白色金牌全模",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE850",
          "price": 496.36,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 安钛克 NE850 金牌（90%）全模组ATX电源 850W 黑白  @京东"
        },
        {
          "id": "psu_利民_tr_sg750_atx3_1_smzdm",
          "category": "电源",
          "model": "TR-SG750 ATX3.1",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91SG750",
          "price": 302.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 利民 额定750W TR-SG750 ATX3.1电源 金牌全模组电源 P @京东"
        },
        {
          "id": "psu_华硕_prime_750g_金牌全模组_smzdm",
          "category": "电源",
          "model": "PRIME 750G 金牌全模组",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%8D%8E%E7%A1%95PRIME%20750G",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[PRIME 750G 金牌全模组]"
        },
        {
          "id": "psu_安钛克_ne1000_白色金牌全模_smzdm",
          "category": "电源",
          "model": "NE1000 白色金牌全模",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%AE%89%E9%92%9B%E5%85%8BNE1000",
          "price": 903.31,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 安钛克 NE系列 NE1000 金牌（90%）全模组电源 1000W  @京东"
        },
        {
          "id": "case_追风者_p400a_黑色_smzdm",
          "category": "机箱",
          "model": "P400A 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%BF%BD%E9%A3%8E%E8%80%85P400A",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[P400A 黑色]"
        },
        {
          "id": "case_乔思伯_松果d41_标准版黑色_smzdm",
          "category": "机箱",
          "model": "松果D41 标准版黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B9%94%E6%80%9D%E4%BC%AFD41",
          "price": 225.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 JONSBO 乔思伯 松果D41 标准版黑色 ATX机箱  @京东"
        },
        {
          "id": "case_先马_趣造2_黑色_smzdm",
          "category": "机箱",
          "model": "趣造2 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%85%88%E9%A9%AC%E8%B6%A3%E9%80%A02",
          "price": 549.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 SAMA 先马 XW280（无风扇版）趣造2黑色 一体式机  @京东"
        },
        {
          "id": "case_航嘉_s960_暴风雪x_黑色_smzdm",
          "category": "机箱",
          "model": "S960 暴风雪X 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%88%AA%E5%98%89S960%E6%9A%B4%E9%A3%8E%E9%9B%AA",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[S960 暴风雪X 黑色]"
        },
        {
          "id": "case_航嘉_s960_暴风雪x_白色_smzdm",
          "category": "机箱",
          "model": "S960 暴风雪X 白色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%88%AA%E5%98%89S960%E7%99%BD%E8%89%B2",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[S960 暴风雪X 白色]"
        },
        {
          "id": "case_先马_趣造2_air_黑色_smzdm",
          "category": "机箱",
          "model": "趣造2 Air 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%85%88%E9%A9%AC%E8%B6%A3%E9%80%A02Air",
          "price": 199.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 先马 趣造2air黑色 桌面matx台式电脑小机箱  @京东"
        },
        {
          "id": "cooler_利民_pa120_se_argb_smzdm",
          "category": "CPU散热器",
          "model": "PA120 SE ARGB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91PA120",
          "price": 177.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 利民 PA120SE ARGB 155mm 风冷散热器 白色  @京东"
        },
        {
          "id": "cooler_九州风神_冰堡垒360_数显版_smzdm",
          "category": "CPU散热器",
          "model": "冰堡垒360 数显版",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B9%9D%E5%B7%9E%E9%A3%8E%E7%A5%9E%E5%86%B0%E5%A0%A1%E5%9E%92360",
          "price": 699.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 文章 用九州风神冰堡垒360数显版！还有什么U压不住？ 使用评测风扇噪音数码配件 @"
        },
        {
          "id": "cooler_瓦尔基里_c360_rgb_smzdm",
          "category": "CPU散热器",
          "model": "C360-RGB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CC360",
          "price": 386.19,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 瓦尔基里 C360-RGB ARGB 65mm 一体式水冷散热器 黑色  @京东"
        },
        {
          "id": "cooler_瓦尔基里_gl360_smzdm",
          "category": "CPU散热器",
          "model": "GL360",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CGL360",
          "price": 619.1,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 瓦尔基里 GL360 VK 360MM 一体式水冷散热器 钛黑  @京东"
        },
        {
          "id": "cooler_瓦尔基里_c360w_rgb_白色_smzdm",
          "category": "CPU散热器",
          "model": "C360W-RGB 白色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%93%A6%E5%B0%94%E5%9F%BA%E9%87%8CC360%E7%99%BD%E8%89%B2",
          "price": 529.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 VALKYRIE 瓦尔基里 C360W-RGB 一体式水冷散热器 白色  @京东"
        },
        {
          "id": "fan_利民_tl_c12c_smzdm",
          "category": "机箱风扇",
          "model": "TL-C12C",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91TL-C12C",
          "price": 45.9,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 利民 TL-C12C 120mm 机箱散热风扇 3个装  @京东"
        },
        {
          "id": "fan_猫头鹰_nf_a12x25_pwm_smzdm",
          "category": "机箱风扇",
          "model": "NF-A12x25 PWM",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%8C%AB%E5%A4%B4%E9%B9%B0NF-A12x25",
          "price": 180.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 noctua 猫头鹰 NF-A12x25 PWM 120mm 机箱散热风扇 @天猫精选"
        },
        {
          "id": "fan_联力_积木风扇_sl120_3b_黑色_smzdm",
          "category": "机箱风扇",
          "model": "积木风扇 SL120-3B 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%81%94%E5%8A%9B%E7%A7%AF%E6%9C%A8%E9%A3%8E%E6%89%87SL120",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[积木风扇 SL120-3B 黑色]"
        },
        {
          "id": "fan_利民_tl_p12_s_argb_smzdm",
          "category": "机箱风扇",
          "model": "TL-P12-S ARGB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%88%A9%E6%B0%91TL-P12-S",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[TL-P12-S ARGB]"
        },
        {
          "id": "fan_联力_积木风扇三代无线版_黑色_smzdm",
          "category": "机箱风扇",
          "model": "积木风扇三代无线版 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%81%94%E5%8A%9B%E7%A7%AF%E6%9C%A8%E9%A3%8E%E6%89%87%E4%B8%89%E4%BB%A3",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[积木风扇三代无线版 黑色]"
        },
        {
          "id": "monitor_戴尔_u2723qe_27英寸_4k_smzdm",
          "category": "显示器",
          "model": "U2723QE 27英寸 4K",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E6%88%B4%E5%B0%94U2723QE",
          "price": 3599.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 DELL 戴尔 U2723QE 27英寸 4K超高清 IPS Black屏 @京东"
        },
        {
          "id": "monitor_aoc_q27g40e_ws_27英寸_2k_180hz_smzdm",
          "category": "显示器",
          "model": "Q27G40E/WS 27英寸 2K 180Hz",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=AOC%20Q27G40E",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[Q27G40E/WS 27英寸 2K 180Hz]"
        },
        {
          "id": "monitor_微星_pro_max_271qphw_e14_27英寸_2k_smzdm",
          "category": "显示器",
          "model": "PRO MAX 271QPHW E14 27英寸 2K",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%BE%AE%E6%98%9FPRO%20MAX%20271QPHW",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[PRO MAX 271QPHW E14 27英寸 2K]"
        },
        {
          "id": "monitor_飞利浦_evnia_27m2n6550pf_27英寸_woled_smzdm",
          "category": "显示器",
          "model": "EVNIA 27M2N6550PF 27英寸 WOLED",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%A3%9E%E5%88%A9%E6%B5%A627M2N6550PF",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[EVNIA 27M2N6550PF 27英寸 WOLED]"
        },
        {
          "id": "keyboard_罗技_g610_机械键盘_红轴_smzdm",
          "category": "键盘",
          "model": "G610 机械键盘 红轴",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G610",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[G610 机械键盘 红轴]"
        },
        {
          "id": "keyboard_樱桃_mx_3_0s_tkl_红轴_smzdm",
          "category": "键盘",
          "model": "MX 3.0S TKL 红轴",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E6%A8%B1%E6%A1%83MX3.0S",
          "price": 423.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 CHERRY 樱桃 MX3.0S TKL有线机械键盘RGB游戏电竞黑 青  @天猫精选"
        },
        {
          "id": "keyboard_雷蛇_黑寡妇v3_竞技版_绿轴_smzdm",
          "category": "键盘",
          "model": "黑寡妇V3 竞技版 绿轴",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%9B%B7%E8%9B%87%E9%BB%91%E5%AF%A1%E5%A6%87V3",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[黑寡妇V3 竞技版 绿轴]"
        },
        {
          "id": "keyboard_vgn_v98pro_v3_冰川轴_smzdm",
          "category": "键盘",
          "model": "V98Pro V3 冰川轴",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=VGN%20V98Pro",
          "price": 228.1,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 国家补贴：VGN V98Pro V3客制化机械键盘99键无线蓝牙有线三模长 @京东"
        },
        {
          "id": "mouse_罗技_g502_hero_主宰者_smzdm",
          "category": "鼠标",
          "model": "G502 HERO 主宰者",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G502",
          "price": 126.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 罗技 G502 HERO 主宰者 有线鼠标 16000DPI RGB  @天猫精选"
        },
        {
          "id": "mouse_雷蛇_毒蝰v2_pro_专业版_smzdm",
          "category": "鼠标",
          "model": "毒蝰V2 Pro 专业版",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%9B%B7%E8%9B%87%E6%AF%92%E8%9D%B0V2Pro",
          "price": 574.15,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 雷蛇 毒蝰 V2 Pro 专业版 2.4G双模无线鼠标 30000DPI  @京东"
        },
        {
          "id": "mouse_罗技_g_pro_x_superlight_二代_黑色_smzdm",
          "category": "鼠标",
          "model": "G PRO X SUPERLIGHT 二代 黑色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80GPW%E4%BA%8C%E4%BB%A3",
          "price": 569.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 logitech 罗技 G） PRO X SUPERLIGHT无线游戏鼠标 @京东"
        },
        {
          "id": "mouse_罗技_g304_白色_smzdm",
          "category": "鼠标",
          "model": "G304 白色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E7%BD%97%E6%8A%80G304",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[G304 白色]"
        },
        {
          "id": "mouse_达尔优_a900_白色_smzdm",
          "category": "鼠标",
          "model": "A900 白色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E8%BE%BE%E5%B0%94%E4%BC%98A900",
          "price": 197.84,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 创维 取暖器石墨烯速热暖风机家用智能温控语音电暖器大面积升温卧室轻音节能暖 @京东"
        },
        {
          "id": "ram_金士顿_fury_64gb_32gx2__ddr5_6000_超级野兽_白色_smzdm",
          "category": "内存",
          "model": "FURY 64GB(32Gx2) DDR5 6000 超级野兽 白色",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E9%87%91%E5%A3%AB%E9%A1%BFFURY%20DDR5%206000%2032Gx2",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[FURY 64GB(32Gx2) DDR5 6000 超级野兽 白色]"
        },
        {
          "id": "ram_威刚_xpg_龙耀_64g_32gx2__ddr5_6400_d500g_smzdm",
          "category": "内存",
          "model": "XPG 龙耀 64G(32Gx2) DDR5 6400 D500G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%A8%81%E5%88%9AXPG%E9%BE%99%E8%80%80DDR5%206400",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[XPG 龙耀 64G(32Gx2) DDR5 6400 D500G]"
        },
        {
          "id": "hdd_东芝_p300_3tb_hdwd130_smzdm",
          "category": "机械硬盘",
          "model": "P300 3TB HDWD130",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E4%B8%9C%E8%8A%9DP300%203TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[P300 3TB HDWD130]"
        },
        {
          "id": "hdd_希捷_酷狼pro_4tb_st4000nt001_smzdm",
          "category": "机械硬盘",
          "model": "酷狼PRO 4TB ST4000NT001",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E5%B8%8C%E6%8D%B7%E9%85%B7%E7%8B%BCPRO%204TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[酷狼PRO 4TB ST4000NT001]"
        },
        {
          "id": "mb_技嘉_b760m_aorus_elite_ax_小雕_ddr5_smzdm",
          "category": "主板",
          "model": "B760M AORUS ELITE AX 小雕 DDR5",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=%E6%8A%80%E5%98%89B760M%E5%B0%8F%E9%9B%95",
          "price": 1099.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 技嘉 B760雕妹主板DDR5 WIFI B760M AORUS ELIT @京东"
        },
        {
          "id": "monitor_ktc_h27v22_27英寸_2k_165hz_smzdm",
          "category": "显示器",
          "model": "H27V22 27英寸 2K 165Hz",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=KTC%20H27V22",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[H27V22 27英寸 2K 165Hz]"
        },
        {
          "id": "keyboard_rk_r98_三模_烟雨轴v2_火蓝_smzdm",
          "category": "键盘",
          "model": "R98 三模 烟雨轴V2 火蓝",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RK%20R98",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[R98 三模 烟雨轴V2 火蓝]"
        }
      ]
    },
    {
      "fetch_time": "2026-09-09T10:16:25.024795+08:00",
      "items": [
        {
          "id": "CPU_AMD_r7_9800x3d_jd",
          "category": "CPU",
          "model": "R7 9800X3D",
          "platform": "京东",
          "url": "",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "京东搜索未匹配型号[R7 9800X3D]",
          "offers": []
        },
        {
          "id": "CPU_AMD_r9_9950x3d_jd",
          "category": "CPU",
          "model": "R9 9950X3D",
          "platform": "京东",
          "url": "",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "京东搜索未匹配型号[R9 9950X3D]",
          "offers": []
        },
        {
          "id": "CPU_Intel_core_ultra_285k_jd",
          "category": "CPU",
          "model": "Core Ultra 285K",
          "platform": "京东",
          "url": "",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "京东搜索未匹配型号[Core Ultra 285K]",
          "offers": []
        },
        {
          "id": "CPU_AMD_r7_9800x3d_smzdm",
          "category": "CPU",
          "model": "R7 9800X3D",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R7%209800X3D",
          "price": 2619.15,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程  @京东",
          "offers": [
            {
              "price": 2619.15,
              "shop": "京东",
              "time": "06-17 21:27",
              "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
            },
            {
              "price": 2329.0,
              "shop": "拼多多",
              "time": "08-26 13:37",
              "title": "好价 AMD 锐龙 R7 9800X3D散片8核16线程高性能电竞处理器 "
            },
            {
              "price": 2969.0,
              "shop": "京东",
              "time": "09-08 10:45",
              "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
            },
            {
              "price": 2709.15,
              "shop": "京东",
              "time": "06-17 21:12",
              "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
            },
            {
              "price": 2879.1,
              "shop": "京东",
              "time": "06-28 03:10",
              "title": "好价 AMD 锐龙R7-9800X3D CPU 4.7GHz 8核16线程 "
            }
          ]
        },
        {
          "id": "CPU_AMD_r9_9950x3d_smzdm",
          "category": "CPU",
          "model": "R9 9950X3D",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=R9%209950X3D",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[R9 9950X3D]",
          "offers": []
        },
        {
          "id": "CPU_Intel_core_ultra_285k_smzdm",
          "category": "CPU",
          "model": "Core Ultra 285K",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=Core%20Ultra%20285K",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[Core Ultra 285K]",
          "offers": []
        },
        {
          "id": "CPU_Intel_i5-12600kf_smzdm",
          "category": "CPU",
          "model": "i5-12600KF",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=i5-12600KF",
          "price": 834.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 英特尔酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 @拼多多",
          "offers": [
            {
              "price": 834.0,
              "shop": "拼多多",
              "time": "09-01 15:43",
              "title": "好价 英特尔酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 "
            },
            {
              "price": 994.0,
              "shop": "京东",
              "time": null,
              "title": "好价 英特尔 酷睿i5-12600KF CPU 4.9Ghz 10核16线程 "
            },
            {
              "price": 874.0,
              "shop": "拼多多",
              "time": "08-13 18:49",
              "title": "好价 i5 12600KF盒装 酷睿12代 10核16线程全新正品官方联保 "
            },
            {
              "price": 979.0,
              "shop": "京东",
              "time": null,
              "title": "好价 英特尔 酷睿i5-12600KF CPU 4.9Ghz 10核16线程 "
            },
            {
              "price": 864.0,
              "shop": "拼多多",
              "time": "08-23 23:52",
              "title": "好价 英特尔 酷睿i5 12600KF处理器10核心16线程游戏办公高效能装机首选 "
            }
          ]
        },
        {
          "id": "显卡_NVIDIA_rtx_5060ti_16g_smzdm",
          "category": "显卡",
          "model": "RTX 5060Ti 16G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RTX%205060Ti%2016G",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[RTX 5060Ti 16G]",
          "offers": []
        },
        {
          "id": "显卡_NVIDIA_rtx_5070_12g_smzdm",
          "category": "显卡",
          "model": "RTX 5070 12G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RTX%205070%2012G",
          "price": 5599.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 微星 魔龙 GeForce RTX 5070 12G GAMING TRI @京东",
          "offers": [
            {
              "price": 5599.0,
              "shop": "京东",
              "time": "07-19 10:16",
              "title": "好价 微星 魔龙 GeForce RTX 5070 12G GAMING TRIO OC 显卡 "
            }
          ]
        },
        {
          "id": "显卡_NVIDIA_rtx_5070ti_16g_smzdm",
          "category": "显卡",
          "model": "RTX 5070Ti 16G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RTX%205070Ti%2016G",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[RTX 5070Ti 16G]",
          "offers": []
        },
        {
          "id": "显卡_NVIDIA_rtx_5080_16g_smzdm",
          "category": "显卡",
          "model": "RTX 5080 16G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RTX%205080%2016G",
          "price": 13606.43,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC @京东",
          "offers": [
            {
              "price": 13606.43,
              "shop": "京东",
              "time": "09-08 11:36",
              "title": "好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC 16G 显卡 "
            },
            {
              "price": 13606.43,
              "shop": "京东",
              "time": "09-05 12:50",
              "title": "好价 微星 超龙 GeForce RTX 5080 16G SUPRIM SOC 16G 显卡 "
            },
            {
              "price": 10996.0,
              "shop": "京东",
              "time": "06-26 16:33",
              "title": "好价 微星 魔龙 GeForce RTX 5080 16G GAMING TRIO OC 显卡 "
            },
            {
              "price": 10999.0,
              "shop": "京东",
              "time": "07-20 17:26",
              "title": "好价 微星 魔龙 GeForce RTX 5080 16G GAMING TRIO OC 显卡 "
            }
          ]
        },
        {
          "id": "显卡_NVIDIA_rtx_5090_32g_smzdm",
          "category": "显卡",
          "model": "RTX 5090 32G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RTX%205090%2032G",
          "price": 11099.0,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 赋欣U7 270K 深度学习支持双卡RTX 5090 32G GPU服务器 @京东",
          "offers": [
            {
              "price": 11099.0,
              "shop": "京东",
              "time": "07-23 18:46",
              "title": "好价 赋欣U7 270K 深度学习支持双卡RTX 5090 32G GPU服务器 OpenClawAI仿真模拟水冷工作站"
            },
            {
              "price": 38399.0,
              "shop": "京东",
              "time": "07-30 13:30",
              "title": "好价 cloud hin 云轩深度学习工作站GPU显卡 RTX 5090 32G涡轮显卡 "
            }
          ]
        },
        {
          "id": "显卡_AMD_rx_9070xt_16g_smzdm",
          "category": "显卡",
          "model": "RX 9070XT 16G",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=RX%209070XT%2016G",
          "price": 4293.05,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏 @天猫精选",
          "offers": [
            {
              "price": 4293.05,
              "shop": "天猫精选",
              "time": "06-16 11:30",
              "title": "好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
            },
            {
              "price": 3899.0,
              "shop": "抖音商城",
              "time": "06-15 13:32",
              "title": "好价 盈通 RX9070XT 16G 大地之神电竞游戏直播剪辑台式机电脑独立显卡 "
            },
            {
              "price": 4293.05,
              "shop": "天猫精选",
              "time": "06-12 14:15",
              "title": "好价 盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
            },
            {
              "price": 4121.53,
              "shop": "天猫精选",
              "time": "06-12 15:42",
              "title": "好价 国家补贴：盈通 RX9070XT 16G樱瞳水着Atlantis OC 全新电竞游戏直播独立显卡 "
            }
          ]
        },
        {
          "id": "固态硬盘_Samsung_990_pro_2tb_smzdm",
          "category": "固态硬盘",
          "model": "990 PRO 2TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=990%20PRO%202TB",
          "price": 2541.86,
          "price_label": "到手价",
          "original_price": null,
          "status": "success",
          "note": "SMZDM匹配: 好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVM @亚马逊",
          "offers": [
            {
              "price": 2541.86,
              "shop": "亚马逊",
              "time": "06-23 12:46",
              "title": "好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVMe高速传输 M.2 SSD 读速7450"
            },
            {
              "price": 2550.3,
              "shop": "亚马逊",
              "time": "08-21 09:09",
              "title": "好价 Samsung 三星 990 PRO 2TB固态硬盘 PCIe接口 NVMe高速传输 M.2 SSD 读速7450"
            }
          ]
        },
        {
          "id": "固态硬盘_致态_tipro9000_2tb_smzdm",
          "category": "固态硬盘",
          "model": "TiPro9000 2TB",
          "platform": "什么值得买",
          "url": "https://search.smzdm.com/?c=home&s=TiPro9000%202TB",
          "price": null,
          "price_label": null,
          "original_price": null,
          "status": "failed",
          "note": "SMZDM未匹配到型号[TiPro9000 2TB]",
          "offers": []
        }
      ]
    }
  ],
  "generated_at": "2026-09-09T10:17:24.749305+08:00"
};
